/*
    Boost Software License - Version 1.0 - August 17, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include "magic.hpp"
#include "serialization.hpp"

#include <limits>

#ifndef REFLECTOR_AVOID_STL
#include <string>
#endif

#define DECLARE_REFLECTION(name_, type_, template_) class name_: public ITypeReflection {\
public:\
    name_() {}\
    virtual bool deserialize(IErrorHandler* err, IReader* reader, void* p_value) override {\
        type_& value = *reinterpret_cast<type_*>(p_value);\
        return Serializer<type_>::deserialize(err, reader, value);\
    }\
    virtual bool isPolymorphic() override { return false; }\
    virtual const char* typeName(const void* p_value) override { return #type_; }\
    virtual const UUID_t* uuidOrNull(const void* p_value) override { return nullptr; }\
    virtual Tag_t getTag() override { return Serializer<type_>::TAG; }\
    virtual bool serialize(IErrorHandler* err, IWriter* writer, const void* p_value)  override {\
        const type_& value = *reinterpret_cast<const type_*>(p_value);\
        return Serializer<type_>::serialize(err, writer, value);\
    }\
    virtual bool setFromString(IErrorHandler* err, const char* str, size_t strLen,\
            void* p_value) override {\
        type_& value = *reinterpret_cast<type_*>(p_value);\
        return template_::fromString(err, str, strLen, value);\
    }\
    virtual const char* staticTypeName() override { return #type_; }\
    virtual bool toString(IErrorHandler* err, char*& buf, size_t& bufSize, uint32_t fieldMask,\
            const void* p_value) override {\
        const type_& value = *reinterpret_cast<const type_*>(p_value);\
        return template_::toString(err, buf, bufSize, value);\
    }\
};\

#define PUBLISH_REFLECTION(reflection_, type_) \
template <> ITypeReflection* reflectionForType<type_>(type_) {\
    static reflection_ reflection;\
    return &reflection;\
}\
template <> ITypeReflection* reflectionForType2<type_>() {\
    static reflection_ reflection;\
    return &reflection;\
}\

#define DEFINE_REFLECTION(name_, type_, template_) \
    DECLARE_REFLECTION(name_, type_, template_)\
    PUBLISH_REFLECTION(name_, type_)

#define DEFINE_INTEGRAL_REFLECTION(type_) DEFINE_REFLECTION(IntegralReflector_##type_, type_, IntegralReflectionTemplate<type_>)

namespace reflection {  // UUID('c3549467-1615-4087-9829-176a2dc44b76')

class BoolReflectionTemplate {
public:
    static bool fromString(IErrorHandler* err, const char* str, size_t strLen, bool& value_out) {
        char* endptr;
        long asLong = strtol(str, &endptr, 0);

        if (endptr > str)
            value_out = (asLong != 0);
        else
            value_out = (strcmp(str, "false") != 0 && strcmp(str, "False") != 0 && strcmp(str, "FALSE") != 0);

        return true;
    }

    static bool toString(IErrorHandler* err, char*& buf, size_t& bufSize, const bool& value) {
        return value ? bufStringSet(err, buf, bufSize, "true", 4)
                : bufStringSet(err, buf, bufSize, "false", 5);
    }
};

template <typename Int_t>
class IntegralReflectionTemplate {
public:
    typedef typename std::numeric_limits<Int_t> Limits;

    static bool fromString(IErrorHandler* err, const char* str, size_t strLen, Int_t& value_out) {
        if (Limits::is_signed) {
            char* end;
            long asLong = strtol(str, &end, 0);

            if (*end != 0)
                return err->error("IntegerFormatError", "Specified value is not a valid integer."), false;

            if (asLong < (long) Limits::min() || asLong > (long) Limits::max())
                return err->error("IntegerOverflow", "Value is outside the limit for this type."), false;

            value_out = (Int_t) asLong;
            return true;
        }
        else {
            char* end;
            unsigned long asULong = strtoul(str, &end, 0);

            if (*end != 0)
                return err->error("IntegerFormatError", "Specified value is not a valid integer."), false;

            if (asULong < (unsigned long) Limits::min() || asULong > (unsigned long) Limits::max())
                return err->error("IntegerOverflow", "Value is outside the limit for this type."), false;

            value_out = (Int_t) asULong;
            return true;
        }
    }

    static bool toString(IErrorHandler* err, char*& buf, size_t& bufSize, const Int_t& value) {
        if (Limits::is_signed)
            return bufStringPrintf(err, buf, bufSize, "%lld", (long long) value);
        else
            return bufStringPrintf(err, buf, bufSize, "%llu", (unsigned long long) value);
    }
};

#ifndef REFLECTOR_AVOID_STL
template <>
class Serializer<std::string> {
public:
    enum { TAG = TAG_UTF8Z };

    static bool serialize(IErrorHandler* err, IWriter* writer, const std::string& value) {
        return writeTag(err, writer, TAG) && writer->write(err, value.c_str(), value.length() + 1);
    }

    static bool deserialize(IErrorHandler* err, IReader* reader, std::string& value_out) {
        if (!checkTag(err, reader, TAG))
            return false;

        char next;

        value_out = "";

        do {
            if (!reader->read(err, &next, sizeof(next)))
                return false;

            if (next == 0)
                break;
            else
                value_out.append(1, next);
        }
        while (true);

        return true;
    }
};


class StdStringReflectionTemplate {
public:
    static bool fromString(IErrorHandler* err, const char* str, size_t strLen, std::string& value_out) {
        value_out = str;
        return true;
    }

    static bool toString(IErrorHandler* err, char*& buf, size_t& bufSize, const std::string& value) {
        return bufStringSet(err, buf, bufSize, value.c_str(), value.length());
    }
};
#endif

DEFINE_REFLECTION(BoolReflection, bool, BoolReflectionTemplate)
DEFINE_INTEGRAL_REFLECTION(uint8_t)
DEFINE_INTEGRAL_REFLECTION(int8_t)
DEFINE_INTEGRAL_REFLECTION(uint16_t)
DEFINE_INTEGRAL_REFLECTION(int16_t)
DEFINE_INTEGRAL_REFLECTION(uint32_t)
DEFINE_INTEGRAL_REFLECTION(int32_t)
DEFINE_INTEGRAL_REFLECTION(uint64_t)
DEFINE_INTEGRAL_REFLECTION(int64_t)

#ifndef REFLECTOR_AVOID_STL
DEFINE_REFLECTION(StdStringReflection, std::string, StdStringReflectionTemplate)
#endif
}
