/*
    Boost Software License - Version 1.0 - August 17, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace reflection {  // UUID('c3549467-1615-4087-9829-176a2dc44b76')

class AllocGuard {
public:
    template <typename T>
    AllocGuard(T*& ptr) : ptr((void*&) ptr) {
    }

    ~AllocGuard() {
        free(ptr);
        ptr = nullptr;
    }

    void*& ptr;
};

struct BufString_t {
    char* buf;
    size_t bufSize;

    BufString_t() : buf(nullptr), bufSize(0) {}
    ~BufString_t() { free(buf); }
};

template <typename IErrorHandler>
bool ensureSize(IErrorHandler* err, char*& buf, size_t& bufSize, size_t newBufSize) {
    if (newBufSize > bufSize) {
        newBufSize = (newBufSize + 31) & ~31;     // align to 32 bytes

        char* newBuf = (char*) realloc(buf, newBufSize);

        if (newBuf == nullptr) {
            return err->allocationError("reflection::ensureSize"), false;
        }

        buf = newBuf;
        bufSize = newBufSize;
    }

    return true;
}

template <typename IErrorHandler>
bool bufStringSet(IErrorHandler* err, char*& buf, size_t& bufSize, const char* str, size_t strLen) {
    size_t newBufSize = strLen + 1;

    if (!ensureSize(err, buf, bufSize, newBufSize))
        return false;

    memcpy(buf, str, strLen + 1);
    return true;
}

template <typename IErrorHandler>
bool bufStringAppend(IErrorHandler* err, char*& buf, size_t& bufSize, const char* str, size_t strLen) {
    size_t len = strlen(buf);
    size_t newBufSize = len + strLen + 1;

    if (!ensureSize(err, buf, bufSize, newBufSize))
        return false;

    memcpy(buf + len, str, strLen + 1);
    return true;
}

template <typename IErrorHandler>
bool bufStringPrintf(IErrorHandler* err, char*& buf, size_t& bufSize, const char* format, ...) {
    va_list args;

    va_start(args, format);
    int length = vsnprintf(nullptr, 0, format, args);
    va_end(args);

    if (length < 0)
        return err->error("PrintfError", "An error occured in `vsnprintf`."), false;

    size_t newBufSize = length + 1;

    if (!ensureSize(err, buf, bufSize, newBufSize))
        return false;

    va_start(args, format);
    length = vsnprintf(buf, bufSize, format, args);
    va_end(args);

    if (length < 0)
        return err->error("PrintfError", "An error occured in `vsnprintf`."), false;

    return true;
}
}
