'''
    Boost Software License - Version 1.0 - August 17, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
'''

MAX_ARGS = 10

def generate_RPC_SERIALIZED_n(num_args):
    print('#define RPC_SERIALIZED_%d(localName_, functionName_)\\' % num_args)
    print('inline decltype(::reflection::returnValueOf(functionName_)) localName_(\\')

    for i in range(0, num_args):
        print('        decltype(::reflection::arg%dTypeIn(functionName_)) const& arg%d' % (i, i), end='')
        if i + 1 < num_args: print(',\\')

    print(') {\\')
    print('    return ::rpc::rpcSerializedCall<decltype(::reflection::returnValueOf(functionName_))>(\\')
    print('             ' + ', '.join(['#functionName_'] + list('arg%d' % i for i in range(0, num_args))) + ');\\')

    print('}')
    print()

def generate_rpcSerializedCall(num_args):
    template_args = 'typename Return'

    for i in range(0, num_args):
        if template_args != '': template_args += ', '
        template_args += 'typename Arg%d' % i

    print('template <' + template_args + '>')
    print('Return rpcSerializedCall(')
    print('        ' + ', '.join(['const char* functionName'] + list('Arg%d const& arg%d' % (i, i) for i in range(0, num_args))) + ') {')
    print('    IWriter* writer;')
    print('    IReader* reader;')
    print('')
    print('    assert(beginRPC(functionName, writer, reader));')
    print('')

    for i in range(0, num_args):
        print('    assert(reflectSerialize(arg%d, writer));' % i)
        if i + 1 == num_args: print('')

    print('    assert(invokeRPC());')
    print('')
    print('    Return result;')
    print('    assert(reflectDeserialize(result, reader));')
    print('')
    print('    endRPC();')
    print('    return result;')
    print('}')
    print('')

def generate_rpcSerializedExecute(num_args):
    template_args = 'typename Return'
    arg_types = ''

    for i in range(0, num_args):
        if template_args != '': template_args += ', '
        if arg_types != '': arg_types += ', '

        template_args += 'typename Arg%d' % i
        arg_types += 'Arg%d' % i

    func_variable = 'Return (*function)(' + arg_types + ')'

    print('template <' + template_args + '>')

    print('bool rpcSerializedExecute(' + func_variable + ', IReader* reader, IWriter* writer) {')
    for i in range(0, num_args):
        print('    std::remove_reference<Arg%d>::type arg%d;' % (i, i))
        if i + 1 == num_args: print('')

    for i in range(0, num_args):
        print('    if (!reflectDeserialize(arg%d, reader)) return false;' % i)
        if i + 1 == num_args: print('')

    print('    const Return result = function(' + ', '.join('arg%d' % i for i in range(0, num_args)) + ');')
    print('')
    print('    if (!reflectSerialize(result, writer)) return false;')
    print('')
    print('    return true;')
    print('}')
    print('')

print('#pragma once')
print()
print('// Generated by gen_rpc_header.py')
print()
print('#include "function.hpp"')
print()

print('namespace rpc {')
print()

for num_args in range(0, MAX_ARGS + 1):
    generate_RPC_SERIALIZED_n(num_args)
    generate_rpcSerializedCall(num_args)
    generate_rpcSerializedExecute(num_args)

print('}')
